### ISSUE TITLE
📖 Update HBN EMA to match NIMH EMA content

### ISSUE THREAD

**Issue by shnizzedy** [ChildMindInstitute/reproschema#19]
Blocked by https://github.com/ChildMindInstitute/mindlogger-app-backend/issues/236,

Ref [HBN EMA Illustrations](https://docs.google.com/spreadsheets/d/17vzMHJWMlHo5ujNZS8R0R6dgywBr-ZfYmNaD3s5yYuQ) (current content), [Questionnaires for MindLogger](https://docs.google.com/spreadsheets/d/19vhRh-6HsEQ5CIZ61EfVXabj_4KVvZQq7RBq8wZ92Qw#gid=936600812) (target content)

**Comment by binarybottle** [comment]
ChildMindInstitute/mindlogger-app-backend#236 is closed, so closing this issue.
