### ISSUE TITLE
Events Question Does Not Give User Correct Options

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/reproschema#22]
Expected Results: User is able to pick the event that affected him or her the most 
Actual Results: User can only select Okay

Environment: iPhone 6s 13.3/ v0.9.11 - EMA Assessment (Morning) NIMH

![File.jpg](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/af94e4c6-066b-4b18-b88c-23f0d8619608)

**Comment by shnizzedy** [comment]
What would resolve this issue? No options? Option to refuse?

**Comment by WorldImpex** [comment]
Change text to "Okay, I am thinking about that event."

**Comment by hotavocado** [comment]
This item is meant to be a 'static' item. I changed it to radio button for testing purposes on the online schema previewer (which had no skip option), but it's back to 'static' now. It still doesn't parse but you're able to skip it. See: https://github.com/ChildMindInstitute/reproschema/issues/23

**Comment by WorldImpex** [comment]
Fixed in https://github.com/ChildMindInstitute/reproschema/issues/23
