### ISSUE TITLE
Single-Selection Conditional Logic Error

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/reproschema#26]
Expected Behavior: If a user selects Yes or No to certain questions the following question is relevant to that answer 
Actual Behavior: The following question does not make sense for the input from the user 

Step 1 
![image.png](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/4cb0f03f-8b1f-45e5-abd5-78dfe0ff4d0c)
Step 2 
![image.png](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/4d439c81-c78e-44d8-b5c1-2dfaedfd2c19)

[More Examples Here](https://matter-lab.slack.com/archives/CDV3HDV1S/p1579668650023900)

**Comment by henryrossiter** [comment]
The visibility logic is specified in the schema, not the app. @WorldImpex what schema is this from? Are you experiencing this behavior on more than one item?

**Comment by WorldImpex** [comment]
@binarybottle After you update your applet, could you test and see if you can recreate this?

**Comment by WorldImpex** [comment]
I can confirm after updating my cache that under NIMH content 2, the logic is not working. Samuel confirmed that the code is there 

![ezgif-7-b62a958f8052](https://user-images.githubusercontent.com/22243307/72917116-3e77d300-3d11-11ea-8e35-7512b8db7e47.gif)

**Comment by WorldImpex** [comment]
fixed 
![ezgif-7-a0659b576265](https://user-images.githubusercontent.com/22243307/72993627-b1da1d00-3dc3-11ea-83cd-d83212ed7bf5.gif)
